//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此原始程式碼由 xsd 版本=4.6.1055.0 自動產生。
// 
namespace XSDVAL.Traffic.XSD
{
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ptx.transportdata.tw/standard/schema/TIX")]
    [System.Xml.Serialization.XmlRootAttribute("VDList", Namespace="http://ptx.transportdata.tw/standard/schema/TIX", IsNullable=false)]
    public partial class VDListType {
        
        private System.DateTime updateTimeField;
        
        private int updateIntervalField;
        
        private AuthorityCodeEnum authorityCodeField;
        
        private VDType[] vDsField;
        
        public VDListType() {
            this.updateIntervalField = 86400;
        }
        
        /// <remarks/>
        public System.DateTime UpdateTime {
            get {
                return this.updateTimeField;
            }
            set {
                this.updateTimeField = value;
            }
        }
        
        /// <remarks/>
        public int UpdateInterval {
            get {
                return this.updateIntervalField;
            }
            set {
                this.updateIntervalField = value;
            }
        }
        
        /// <remarks/>
        public AuthorityCodeEnum AuthorityCode {
            get {
                return this.authorityCodeField;
            }
            set {
                this.authorityCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("VD", IsNullable=false)]
        public VDType[] VDs {
            get {
                return this.vDsField;
            }
            set {
                this.vDsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ptx.transportdata.tw/standard/schema/TIX")]
    public enum AuthorityCodeEnum {
        
        /// <remarks/>
        TPE,
        
        /// <remarks/>
        KHH,
        
        /// <remarks/>
        NWT,
        
        /// <remarks/>
        TXG,
        
        /// <remarks/>
        TNN,
        
        /// <remarks/>
        TAO,
        
        /// <remarks/>
        ILA,
        
        /// <remarks/>
        HSQ,
        
        /// <remarks/>
        MIA,
        
        /// <remarks/>
        CHA,
        
        /// <remarks/>
        NAN,
        
        /// <remarks/>
        YUN,
        
        /// <remarks/>
        CYQ,
        
        /// <remarks/>
        PIF,
        
        /// <remarks/>
        TTT,
        
        /// <remarks/>
        HUA,
        
        /// <remarks/>
        PEN,
        
        /// <remarks/>
        KEE,
        
        /// <remarks/>
        HSZ,
        
        /// <remarks/>
        CYI,
        
        /// <remarks/>
        KIN,
        
        /// <remarks/>
        LIE,
        
        /// <remarks/>
        NFB,
        
        /// <remarks/>
        THB,
        
        /// <remarks/>
        HCSP,
        
        /// <remarks/>
        CTSP,
        
        /// <remarks/>
        STSP,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ptx.transportdata.tw/standard/schema/TIX")]
    public partial class VDType {
        
        private string vDIDField;
        
        private SubAuthorityCodeEnum subAuthorityCodeField;
        
        private bool subAuthorityCodeFieldSpecified;
        
        private BiDirectionalEnum biDirectionalField;
        
        private DetectionLinkType[] detectionLinksField;
        
        private VDTypeEnum vDType1Field;
        
        private LocationTypeEnum locationTypeField;
        
        private bool locationTypeFieldSpecified;
        
        private DetectionTypeEnum detectionTypeField;
        
        private double positionLonField;
        
        private double positionLatField;
        
        private string roadIDField;
        
        private string roadNameField;
        
        private RoadClassEnum roadClassField;
        
        private bool roadClassFieldSpecified;
        
        private RoadSectionType roadSectionField;
        
        private string locationMileField;
        
        private string layoutMapURLField;
        
        /// <remarks/>
        public string VDID {
            get {
                return this.vDIDField;
            }
            set {
                this.vDIDField = value;
            }
        }
        
        /// <remarks/>
        public SubAuthorityCodeEnum SubAuthorityCode {
            get {
                return this.subAuthorityCodeField;
            }
            set {
                this.subAuthorityCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SubAuthorityCodeSpecified {
            get {
                return this.subAuthorityCodeFieldSpecified;
            }
            set {
                this.subAuthorityCodeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public BiDirectionalEnum BiDirectional {
            get {
                return this.biDirectionalField;
            }
            set {
                this.biDirectionalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("DetectionLink", IsNullable=false)]
        public DetectionLinkType[] DetectionLinks {
            get {
                return this.detectionLinksField;
            }
            set {
                this.detectionLinksField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("VDType")]
        public VDTypeEnum VDType1 {
            get {
                return this.vDType1Field;
            }
            set {
                this.vDType1Field = value;
            }
        }
        
        /// <remarks/>
        public LocationTypeEnum LocationType {
            get {
                return this.locationTypeField;
            }
            set {
                this.locationTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LocationTypeSpecified {
            get {
                return this.locationTypeFieldSpecified;
            }
            set {
                this.locationTypeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public DetectionTypeEnum DetectionType {
            get {
                return this.detectionTypeField;
            }
            set {
                this.detectionTypeField = value;
            }
        }
        
        /// <remarks/>
        public double PositionLon {
            get {
                return this.positionLonField;
            }
            set {
                this.positionLonField = value;
            }
        }
        
        /// <remarks/>
        public double PositionLat {
            get {
                return this.positionLatField;
            }
            set {
                this.positionLatField = value;
            }
        }
        
        /// <remarks/>
        public string RoadID {
            get {
                return this.roadIDField;
            }
            set {
                this.roadIDField = value;
            }
        }
        
        /// <remarks/>
        public string RoadName {
            get {
                return this.roadNameField;
            }
            set {
                this.roadNameField = value;
            }
        }
        
        /// <remarks/>
        public RoadClassEnum RoadClass {
            get {
                return this.roadClassField;
            }
            set {
                this.roadClassField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RoadClassSpecified {
            get {
                return this.roadClassFieldSpecified;
            }
            set {
                this.roadClassFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public RoadSectionType RoadSection {
            get {
                return this.roadSectionField;
            }
            set {
                this.roadSectionField = value;
            }
        }
        
        /// <remarks/>
        public string LocationMile {
            get {
                return this.locationMileField;
            }
            set {
                this.locationMileField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI")]
        public string LayoutMapURL {
            get {
                return this.layoutMapURLField;
            }
            set {
                this.layoutMapURLField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ptx.transportdata.tw/standard/schema/TIX")]
    public enum SubAuthorityCodeEnum {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("NFB-NR")]
        NFBNR,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("NFB-CR")]
        NFBCR,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("NFB-SR")]
        NFBSR,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("NFB-PL")]
        NFBPL,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("THB-1R")]
        THB1R,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("THB-2R")]
        THB2R,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("THB-3R")]
        THB3R,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("THB-4R")]
        THB4R,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("THB-5R")]
        THB5R,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("THB-SH")]
        THBSH,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("THB-WS")]
        THBWS,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ptx.transportdata.tw/standard/schema/TIX")]
    public enum BiDirectionalEnum {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0")]
        Item0,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ptx.transportdata.tw/standard/schema/TIX")]
    public partial class DetectionLinkType {
        
        private string linkIDField;
        
        private BearingEnum bearingField;
        
        private RoadDirectionEnum roadDirectionField;
        
        private int laneNumField;
        
        private int actualLaneNumField;
        
        /// <remarks/>
        public string LinkID {
            get {
                return this.linkIDField;
            }
            set {
                this.linkIDField = value;
            }
        }
        
        /// <remarks/>
        public BearingEnum Bearing {
            get {
                return this.bearingField;
            }
            set {
                this.bearingField = value;
            }
        }
        
        /// <remarks/>
        public RoadDirectionEnum RoadDirection {
            get {
                return this.roadDirectionField;
            }
            set {
                this.roadDirectionField = value;
            }
        }
        
        /// <remarks/>
        public int LaneNum {
            get {
                return this.laneNumField;
            }
            set {
                this.laneNumField = value;
            }
        }
        
        /// <remarks/>
        public int ActualLaneNum {
            get {
                return this.actualLaneNumField;
            }
            set {
                this.actualLaneNumField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ptx.transportdata.tw/standard/schema/TIX")]
    public enum BearingEnum {
        
        /// <remarks/>
        N,
        
        /// <remarks/>
        E,
        
        /// <remarks/>
        S,
        
        /// <remarks/>
        W,
        
        /// <remarks/>
        NE,
        
        /// <remarks/>
        SE,
        
        /// <remarks/>
        SW,
        
        /// <remarks/>
        NW,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ptx.transportdata.tw/standard/schema/TIX")]
    public enum RoadDirectionEnum {
        
        /// <remarks/>
        N,
        
        /// <remarks/>
        E,
        
        /// <remarks/>
        S,
        
        /// <remarks/>
        W,
        
        /// <remarks/>
        NE,
        
        /// <remarks/>
        SE,
        
        /// <remarks/>
        SW,
        
        /// <remarks/>
        NW,
        
        /// <remarks/>
        A,
        
        /// <remarks/>
        CW,
        
        /// <remarks/>
        CCW,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ptx.transportdata.tw/standard/schema/TIX")]
    public partial class RoadSectionType {
        
        private string startField;
        
        private string endField;
        
        /// <remarks/>
        public string Start {
            get {
                return this.startField;
            }
            set {
                this.startField = value;
            }
        }
        
        /// <remarks/>
        public string End {
            get {
                return this.endField;
            }
            set {
                this.endField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ptx.transportdata.tw/standard/schema/TIX")]
    public enum VDTypeEnum {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3")]
        Item3,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("4")]
        Item4,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("5")]
        Item5,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("6")]
        Item6,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ptx.transportdata.tw/standard/schema/TIX")]
    public enum LocationTypeEnum {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3")]
        Item3,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("4")]
        Item4,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("5")]
        Item5,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("6")]
        Item6,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ptx.transportdata.tw/standard/schema/TIX")]
    public enum DetectionTypeEnum {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3")]
        Item3,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("4")]
        Item4,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ptx.transportdata.tw/standard/schema/TIX")]
    public enum RoadClassEnum {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0")]
        Item0,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3")]
        Item3,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("4")]
        Item4,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("5")]
        Item5,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("6")]
        Item6,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("7")]
        Item7,
    }
}
